### ISSUE TITLE
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.

### ISSUE THREAD

**Issue by Zeno97** [Hitman666/cordova-ios-voip-push#19]
Hi i have configured my app with this plugin and importing pushkit framework. After that i have used simplepush.php to make a test and in the debugger i have this error:
`Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.`
I need a voip notification even if the app is terminated like whatsapp, then why i have to post an incoming call?

**Comment by NikolaBreznjak** [comment]
Because those are the new rules by Apple. You can't use the VoIP push unless you're going to show the onCall screen. Hope this helps.

**Comment by Zeno97** [comment]
Ok then how can I show push notifications for instant messages like whatsapp? There is some api or framework for that?

**Comment by NikolaBreznjak** [comment]
With the normal push plugin. Start with this: https://ionicframework.com/docs/native/push

**Comment by Zeno97** [comment]
IM like WhatsApp works even if app is terminated. Standard push notifications work only if app is running in background or foreground but not when app is terminated.

Thanks for your time really appreciate it

**Comment by Zeno97** [comment]
Do you have any idea of how whatsapp show notifications when app is terminated without pushkit and without normal push?

**Comment by NikolaBreznjak** [comment]
Yes, by using normal push notifications and not VoIP push notifications.
