### ISSUE TITLE
App closed - background push

### ISSUE THREAD

**Issue by jQrgen** [Hitman666/cordova-ios-voip-push#4]
Hello

Is this cordova plugin compatible with receiving VOIP-background (App completely turned off) pushes and spawning background jobs in javascript which can call other cordova plugins?

Thanks

**Comment by NikolaBreznjak** [comment]
Yes.

**Comment by jQrgen** [comment]
THanks :)

**Comment by NikolaBreznjak** [comment]
You're welcome!

**Comment by jQrgen** [comment]
Merry xmas :)

**Comment by NikolaBreznjak** [comment]
Thank you, to you too!! 💪
